/* tslint:disable */
/* eslint-disable */
/**
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetAccountAllOfMarketingAutomation } from './GetAccountAllOfMarketingAutomation';
import {
	GetAccountAllOfMarketingAutomationFromJSON,
	GetAccountAllOfMarketingAutomationFromJSONTyped,
	GetAccountAllOfMarketingAutomationToJSON
} from './GetAccountAllOfMarketingAutomation';
import type { GetAccountAllOfPlan } from './GetAccountAllOfPlan';
import {
	GetAccountAllOfPlanFromJSON,
	GetAccountAllOfPlanFromJSONTyped,
	GetAccountAllOfPlanToJSON
} from './GetAccountAllOfPlan';
import type { GetAccountAllOfRelay } from './GetAccountAllOfRelay';
import {
	GetAccountAllOfRelayFromJSON,
	GetAccountAllOfRelayFromJSONTyped,
	GetAccountAllOfRelayToJSON
} from './GetAccountAllOfRelay';

/**
 *
 * @export
 * @interface GetAccountAllOf
 */
export interface GetAccountAllOf {
	/**
	 * Information about your plans and credits
	 * @type {Array<GetAccountAllOfPlan>}
	 * @memberof GetAccountAllOf
	 */
	plan: Array<GetAccountAllOfPlan>;
	/**
	 *
	 * @type {GetAccountAllOfRelay}
	 * @memberof GetAccountAllOf
	 */
	relay: GetAccountAllOfRelay;
	/**
	 *
	 * @type {GetAccountAllOfMarketingAutomation}
	 * @memberof GetAccountAllOf
	 */
	marketingAutomation?: GetAccountAllOfMarketingAutomation;
}

/**
 * Check if a given object implements the GetAccountAllOf interface.
 */
export function instanceOfGetAccountAllOf(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'plan' in value;
	isInstance = isInstance && 'relay' in value;

	return isInstance;
}

export function GetAccountAllOfFromJSON(json: any): GetAccountAllOf {
	return GetAccountAllOfFromJSONTyped(json, false);
}

export function GetAccountAllOfFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): GetAccountAllOf {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		plan: (json['plan'] as Array<any>).map(GetAccountAllOfPlanFromJSON),
		relay: GetAccountAllOfRelayFromJSON(json['relay']),
		marketingAutomation: !exists(json, 'marketingAutomation')
			? undefined
			: GetAccountAllOfMarketingAutomationFromJSON(json['marketingAutomation'])
	};
}

export function GetAccountAllOfToJSON(value?: GetAccountAllOf | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		plan: (value.plan as Array<any>).map(GetAccountAllOfPlanToJSON),
		relay: GetAccountAllOfRelayToJSON(value.relay),
		marketingAutomation: GetAccountAllOfMarketingAutomationToJSON(value.marketingAutomation)
	};
}
