/* tslint:disable */
/* eslint-disable */
/**
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetEmailCampaignsCampaignsInnerAllOfRecipients } from './GetEmailCampaignsCampaignsInnerAllOfRecipients';
import {
	GetEmailCampaignsCampaignsInnerAllOfRecipientsFromJSON,
	GetEmailCampaignsCampaignsInnerAllOfRecipientsFromJSONTyped,
	GetEmailCampaignsCampaignsInnerAllOfRecipientsToJSON
} from './GetEmailCampaignsCampaignsInnerAllOfRecipients';
import type { GetEmailCampaignsCampaignsInnerAllOfStatistics } from './GetEmailCampaignsCampaignsInnerAllOfStatistics';
import {
	GetEmailCampaignsCampaignsInnerAllOfStatisticsFromJSON,
	GetEmailCampaignsCampaignsInnerAllOfStatisticsFromJSONTyped,
	GetEmailCampaignsCampaignsInnerAllOfStatisticsToJSON
} from './GetEmailCampaignsCampaignsInnerAllOfStatistics';

/**
 *
 * @export
 * @interface GetEmailCampaignsCampaignsInnerAllOf
 */
export interface GetEmailCampaignsCampaignsInnerAllOf {
	/**
	 *
	 * @type {GetEmailCampaignsCampaignsInnerAllOfRecipients}
	 * @memberof GetEmailCampaignsCampaignsInnerAllOf
	 */
	recipients: GetEmailCampaignsCampaignsInnerAllOfRecipients;
	/**
	 *
	 * @type {GetEmailCampaignsCampaignsInnerAllOfStatistics}
	 * @memberof GetEmailCampaignsCampaignsInnerAllOf
	 */
	statistics: GetEmailCampaignsCampaignsInnerAllOfStatistics;
	/**
	 * Link to share the campaign on social medias
	 * @type {string}
	 * @memberof GetEmailCampaignsCampaignsInnerAllOf
	 */
	shareLink?: string;
}

/**
 * Check if a given object implements the GetEmailCampaignsCampaignsInnerAllOf interface.
 */
export function instanceOfGetEmailCampaignsCampaignsInnerAllOf(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'recipients' in value;
	isInstance = isInstance && 'statistics' in value;

	return isInstance;
}

export function GetEmailCampaignsCampaignsInnerAllOfFromJSON(
	json: any
): GetEmailCampaignsCampaignsInnerAllOf {
	return GetEmailCampaignsCampaignsInnerAllOfFromJSONTyped(json, false);
}

export function GetEmailCampaignsCampaignsInnerAllOfFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): GetEmailCampaignsCampaignsInnerAllOf {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		recipients: GetEmailCampaignsCampaignsInnerAllOfRecipientsFromJSON(json['recipients']),
		statistics: GetEmailCampaignsCampaignsInnerAllOfStatisticsFromJSON(json['statistics']),
		shareLink: !exists(json, 'shareLink') ? undefined : json['shareLink']
	};
}

export function GetEmailCampaignsCampaignsInnerAllOfToJSON(
	value?: GetEmailCampaignsCampaignsInnerAllOf | null
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		recipients: GetEmailCampaignsCampaignsInnerAllOfRecipientsToJSON(value.recipients),
		statistics: GetEmailCampaignsCampaignsInnerAllOfStatisticsToJSON(value.statistics),
		shareLink: value.shareLink
	};
}
