/* tslint:disable */
/* eslint-disable */
/**
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetEmailCampaignsCampaignsInnerAllOfRecipients } from './GetEmailCampaignsCampaignsInnerAllOfRecipients';
import {
	GetEmailCampaignsCampaignsInnerAllOfRecipientsFromJSON,
	GetEmailCampaignsCampaignsInnerAllOfRecipientsFromJSONTyped,
	GetEmailCampaignsCampaignsInnerAllOfRecipientsToJSON
} from './GetEmailCampaignsCampaignsInnerAllOfRecipients';
import type { GetSmsCampaignsCampaignsInnerAllOfStatistics } from './GetSmsCampaignsCampaignsInnerAllOfStatistics';
import {
	GetSmsCampaignsCampaignsInnerAllOfStatisticsFromJSON,
	GetSmsCampaignsCampaignsInnerAllOfStatisticsFromJSONTyped,
	GetSmsCampaignsCampaignsInnerAllOfStatisticsToJSON
} from './GetSmsCampaignsCampaignsInnerAllOfStatistics';

/**
 *
 * @export
 * @interface GetSmsCampaignsCampaignsInnerAllOf
 */
export interface GetSmsCampaignsCampaignsInnerAllOf {
	/**
	 *
	 * @type {GetEmailCampaignsCampaignsInnerAllOfRecipients}
	 * @memberof GetSmsCampaignsCampaignsInnerAllOf
	 */
	recipients: GetEmailCampaignsCampaignsInnerAllOfRecipients;
	/**
	 *
	 * @type {GetSmsCampaignsCampaignsInnerAllOfStatistics}
	 * @memberof GetSmsCampaignsCampaignsInnerAllOf
	 */
	statistics: GetSmsCampaignsCampaignsInnerAllOfStatistics;
}

/**
 * Check if a given object implements the GetSmsCampaignsCampaignsInnerAllOf interface.
 */
export function instanceOfGetSmsCampaignsCampaignsInnerAllOf(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'recipients' in value;
	isInstance = isInstance && 'statistics' in value;

	return isInstance;
}

export function GetSmsCampaignsCampaignsInnerAllOfFromJSON(
	json: any
): GetSmsCampaignsCampaignsInnerAllOf {
	return GetSmsCampaignsCampaignsInnerAllOfFromJSONTyped(json, false);
}

export function GetSmsCampaignsCampaignsInnerAllOfFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): GetSmsCampaignsCampaignsInnerAllOf {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		recipients: GetEmailCampaignsCampaignsInnerAllOfRecipientsFromJSON(json['recipients']),
		statistics: GetSmsCampaignsCampaignsInnerAllOfStatisticsFromJSON(json['statistics'])
	};
}

export function GetSmsCampaignsCampaignsInnerAllOfToJSON(
	value?: GetSmsCampaignsCampaignsInnerAllOf | null
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		recipients: GetEmailCampaignsCampaignsInnerAllOfRecipientsToJSON(value.recipients),
		statistics: GetSmsCampaignsCampaignsInnerAllOfStatisticsToJSON(value.statistics)
	};
}
