/* tslint:disable */
/* eslint-disable */
/**
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetWebhooksWebhooksInner
 */
export interface GetWebhooksWebhooksInner {
	/**
	 * URL of the webhook
	 * @type {string}
	 * @memberof GetWebhooksWebhooksInner
	 */
	url: string;
	/**
	 * ID of the webhook
	 * @type {number}
	 * @memberof GetWebhooksWebhooksInner
	 */
	id: number;
	/**
	 * Description of the webhook
	 * @type {string}
	 * @memberof GetWebhooksWebhooksInner
	 */
	description: string;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof GetWebhooksWebhooksInner
	 */
	events: Array<string>;
	/**
	 * Type of webhook (marketing or transac)
	 * @type {string}
	 * @memberof GetWebhooksWebhooksInner
	 */
	type: GetWebhooksWebhooksInnerTypeEnum;
	/**
	 * Creation UTC date-time of the webhook (YYYY-MM-DDTHH:mm:ss.SSSZ)
	 * @type {Date}
	 * @memberof GetWebhooksWebhooksInner
	 */
	createdAt: Date;
	/**
	 * Last modification UTC date-time of the webhook (YYYY-MM-DDTHH:mm:ss.SSSZ)
	 * @type {Date}
	 * @memberof GetWebhooksWebhooksInner
	 */
	modifiedAt: Date;
}

/**
 * @export
 * @enum {string}
 */
export enum GetWebhooksWebhooksInnerTypeEnum {
	Marketing = 'marketing',
	Transac = 'transac'
}

/**
 * Check if a given object implements the GetWebhooksWebhooksInner interface.
 */
export function instanceOfGetWebhooksWebhooksInner(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'url' in value;
	isInstance = isInstance && 'id' in value;
	isInstance = isInstance && 'description' in value;
	isInstance = isInstance && 'events' in value;
	isInstance = isInstance && 'type' in value;
	isInstance = isInstance && 'createdAt' in value;
	isInstance = isInstance && 'modifiedAt' in value;

	return isInstance;
}

export function GetWebhooksWebhooksInnerFromJSON(json: any): GetWebhooksWebhooksInner {
	return GetWebhooksWebhooksInnerFromJSONTyped(json, false);
}

export function GetWebhooksWebhooksInnerFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): GetWebhooksWebhooksInner {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		url: json['url'],
		id: json['id'],
		description: json['description'],
		events: json['events'],
		type: json['type'],
		createdAt: new Date(json['createdAt']),
		modifiedAt: new Date(json['modifiedAt'])
	};
}

export function GetWebhooksWebhooksInnerToJSON(value?: GetWebhooksWebhooksInner | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		url: value.url,
		id: value.id,
		description: value.description,
		events: value.events,
		type: value.type,
		createdAt: value.createdAt.toISOString(),
		modifiedAt: value.modifiedAt.toISOString()
	};
}
